ben_dev/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'home.views.index'),
    url(r'^hangman/', include('hangman.urls', namespace="hangman")),
    url(r'^plaid/', include('plaid_tester.urls', namespace="plaid_tester")),
    url(r'^admin/', include(admin.site.urls)),

]

blog/urls.py
__author__ = 'benfishman'

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^chumash_parsha/$', views.chumash_parsha_listing, name='chumash_parsha_listing'),
    url(r'^chumash_parsha/(?P<sefer>[-A-Za-z_-]+)/$', views.sefer_parsha_listing, name='sefer_parsha_listing'),
    url(r'^chumash_parsha/questions/(?P<parsha_name>[-A-Za-z_-]+)/$', views.parsha_questions_list, name='parsha_questions_list'),
    url(r'^parsha/question/(?P<question_id>[0-9]+)/$', views.parsha_question_detail, name='parsha_question_detail'),
    url(r'^(?P<slug>[\w\-]+)/$', views.post, name='blog_detail'),
    url(r'^category/(?P<category>[\w\-]+)/$', views.category_post_list, name='category_list'),

]

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=255)

    class Meta:
        ordering = ['-title']

    def __str__(self):
        return u'%s' % self.title


class Section(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return u'%s' % self.title


class Post(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.CharField(max_length=255)
    content = models.TextField()
    published = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category)


    class Meta:
        abstract = True
        ordering = ['-created']

    def __str__(self):
        return u'%s' % self.title

    def get_absolute_url(self):
        print("in here")
        print([self.slug])
        return reverse('blog:blog_detail', args=[self.slug])

    def get_categories(self):
        return ", ".join([c.title for c in self.categories.all()])

    def get_title(self):
        return self.title

class ParshaPost(Post):
    CHUMASH = ((1,'Genesis'),(2,'Exodus'),(3,'Leviticus'),(4,'Deutoronomy'),(5,'Bamidbar'))
    sefer = models.IntegerField(choices=CHUMASH)

    def get_template_suffix(self):
        return 'parsha'

class GemaraPost(Post):
    AMUDS = (
        ('0','A'),
        ('1','B')
    )
    gemara = models.ForeignKey('Gemara', null=True)
    daf = models.IntegerField(default=0, blank=True, null=True)
    amud = models.CharField(max_length=2, choices=AMUDS)

    def get_title(self):
        return self.gemara.title


class Gemara(models.Model):
    title = models.CharField(max_length=100, unique=True)
    seder = models.CharField(max_length=100, unique=True)
    number_of_daf = models.IntegerField(default=0, blank=True, null=True)
    number_of_perakim = models.IntegerField(default=0, blank=True, null=True)

    class Meta:
        ordering = ['-title']

    def __str__(self):
        return u'%s' % self.title

class Person(models.Model):
    name = models.CharField(max_length=100, unique=True)
    date_of_birth = models.DateField(blank=True, null=True)

    def __str__(self):
        return u'%s' % self.name

class Statement(models.Model):
    person = models.ForeignKey(Person, null=True)
    statement = models.TextField()
    gemara_post = models.ForeignKey(GemaraPost, null=True)
    is_challenge = models.BooleanField(default=False)
    is_resolution = models.BooleanField(default=False)
    is_mishnah = models.BooleanField(default=False)
    is_gemara = models.BooleanField(default=False)

    def __str__(self):
        return u'%s' % self.id

class Question(models.Model):
    title = models.CharField(max_length=100, unique=True)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True
        ordering = ['-created']

    def __str__(self):
        return u'%s' % self.title

class ParshaQuestion(Question):
     parsha = models.ForeignKey('Parsha', null=True)


class Chumash(models.Model):
    title = models.CharField(max_length=100, unique=True)
    order = models.IntegerField(default=0, unique=True)

    def __str__(self):
        return u'%s' % self.title

class Parsha(models.Model):
    eng_name = models.CharField(max_length=100, unique=True)
    chumash = models.ForeignKey(Chumash, null=True)
    order = models.IntegerField(default=0, unique=True)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return u'%s' % self.eng_name

    def sefer(self):
        return self.chumash.title

    class Meta:
        ordering = ['order']

blog/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render_to_response, get_object_or_404
from django.db.models import Count
from blog.models import GemaraPost, Category, ParshaPost, Chumash, \
    Parsha, ParshaQuestion
from django.http import HttpResponse

'''
The index view simply lists the categories one could click to look at
FOR NOW
'''


def index(request):
    # posts = Post.objects.filter(published=True)
    categories = Category.objects.all()

    shteig_header = "home"

    # get most recent 5 parsha posts (posts with section == parsha)
    gemara_posts = GemaraPost.objects.all()
    #halacha_posts = Post.objects.filter(section__title__startswith='Halacha')
    return render(request, 'blog/index.html',
                  {'categories': categories, 'gemara_posts': gemara_posts, 'subheader': shteig_header})


def about(request):
    return render(request, 'blog/about.html', context)


def post(request, slug):
    print("post view")
    print("request: " + str(request))
    print("slug: " + slug)
    # get the Post object
    # post = get_object_or_404(GemaraPost, slug=slug)
    post = get_object_or_404(ParshaPost, slug=slug)
    related_posts = GemaraPost.objects.all().exclude(pk=post.pk)

    template_name = 'post-' + post.get_template_suffix() + '.html'

    subheader = post.get_title()
    # now return the rendered template
    return render(request, 'blog/' + template_name,
                  {'post': post, 'subheader': subheader, 'related_posts': related_posts})


def category_post_list(request, category):
    print("category post view")
    print(category)
    posts = Post.objects.filter(categories__title__startswith=category)
    return render(request, 'blog/view_category.html', {'posts': posts})


def chumash_parsha_listing(request):
    # genesis = Parsha.objects.filter(chumash__title__startswith='Genesis').order_by('order')
    chumash = {'Genesis':
                   ['Bereishis', 'Noach', 'Lech Lecha', 'Vayeira', 'Chayei Sara', 'Toldos', 'Vayeitzei', \
                    'Vayishlach', 'Vayeishev', 'Mikeitz', 'Vayigash', 'Vayechi'],
               'Exodus': [],
               'Leviticus': [],
               'Numbers': [],
               'Deuteronomy': ['eikev']
    }
    return render(request, 'blog/chumash-parsha-list.html', {'books': chumash})


def sefer_parsha_listing(request, sefer):
    chumash = {'Genesis':
                   ['Bereishis', 'Noach', 'Lech Lecha', 'Vayeira', 'Chayei Sara', 'Toldos', 'Vayeitzei', \
                    'Vayishlach', 'Vayeishev', 'Miketz', 'Vayigash', 'Vayechi'],
               'Exodus': [],
               'Leviticus': [],
               'Numbers': [],
               'Deuteronomy': ['deuteronomy', 'eikev']
    }
    parshas_with_questions = list(ParshaQuestion.objects.filter(parsha__chumash__title=sefer).values('parsha__eng_name',
                                                                                                'parsha__order').annotate(
        total=Count('parsha__eng_name')).order_by('total'))
    # have to add the rest of the parsha with 0 and their orders
    i = 0
    for parsha in chumash[sefer]:
        # if current parsha is in not returned add it with its totsl set to 0 and order
        if not any(d['parsha__eng_name'] == parsha.lower() for d in parshas_with_questions):
            #print(parsha)
            parshas_with_questions.append( {'parsha__eng_name':parsha,'parsha__order':i,'total':0})
        i+=1
    return render(request, 'blog/sefer_parsha_listing.html', {'parshas': parshas_with_questions, 'sefer': sefer})


def parsha_questions_list(request, parsha_name):
    # get all questions related to parsha id returned in descending order by date creaed

    # convert query string to lower case
    title = parsha_name.title()
    sefer = parsha_to_sefer(parsha_name)
    questions = ParshaQuestion.objects.filter(parsha__eng_name=parsha_name).order_by('created')

    return render(request, 'blog/parsha_questions_list.html', {'questions': questions, 'title':title, 'sefer':sefer})


def parsha_question_detail(request, question_id):
    question = get_object_or_404(ParshaQuestion, pk=question_id)

    # query for other question in selected parsha but exclud current question
    related_question = ParshaQuestion.objects.filter(parsha__eng_name=question.parsha.eng_name).exclude(pk=question.pk)
    return render(request, 'blog/parsha_question_detail.html',
                  {'question': question, 'related_questions': related_question})

def parsha_to_sefer(parsha):
    '''
    : This is a helper function to get the name of the
    : overarching sefer a parsha is in
    :param parsha: string
    :return: name of parent sefer
    '''
    chumash = {'Genesis':
                   ['Bereishis', 'Noach', 'Lech Lecha', 'Vayeira', 'Chayei Sara', 'Toldos', 'Vayeitzei', \
                    'Vayishlach', 'Vayeishev', 'Miketz', 'Vayigash', 'Vayechi'],
               'Exodus': [],
               'Leviticus': [],
               'Numbers': [],
               'Deuteronomy': ['Deuteronomy', 'Eikev']
    }

    for sefer in chumash:
        if parsha.title().replace("_"," ") in chumash[sefer]:
            return sefer
    return False

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% load staticfiles %}

{% block header %}
{% endblock %}

{% block content %}
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis cursus dui. Nam efficitur mauris nisl, vel
        varius ex volutpat eu. Nullam dictum varius aliquet. Sed tristique purus purus, ut condimentum dolor ultrices
        ut. Curabitur ante purus, commodo eu finibus quis, ultricies a sem. Suspendisse id nunc leo. Fusce lobortis
        aliquam tincidunt. Donec vel dui id nibh posuere facilisis faucibus ac leo. Pellentesque quam ipsum, elementum
        vitae facilisis tincidunt, viverra nec tellus. Phasellus mollis dolor et semper molestie. Curabitur ut dui
        sapien. Nunc luctus ante vel neque bibendum cursus. Cum sociis natoque penatibus et magnis dis parturient
        montes, nascetur ridiculus mus.</p>

      <p> Sed in porttitor lacus. Vivamus mattis rhoncus sapien, quis egestas purus vehicula vitae. Curabitur iaculis
        maximus ligula, sed facilisis dui. Vivamus ornare maximus elit non porta. Aenean dictum diam a auctor accumsan.
        Praesent enim metus, posuere in elit vel, iaculis sodales erat. Lorem ipsum dolor sit amet, consectetur
        adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
    </p>
{% endblock %}

blog/templates/blog/base.html
{% load staticfiles %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
<head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <meta charset="utf-8">
    {% block header %}
    {% endblock %}
    <title>
        {% block title %}{% endblock %}
    </title>
</head>
<body>
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand logo" href="{% url 'blog:index' %}">Project Chazarah</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <!--<li><a href="{% url 'blog:chumash_parsha_listing' %}">Parsha</a></li>-->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Parsha <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'blog:sefer_parsha_listing' 'Genesis' %}">Bereishis</a></li>
                        <li><a href="{% url 'blog:sefer_parsha_listing' 'Exodus' %}">Shemos</a></li>
                        <li><a href="{% url 'blog:sefer_parsha_listing' 'Leviticus' %}">Vayikra</a></li>
                        <li><a href="{% url 'blog:sefer_parsha_listing' 'Numbers' %}">Bamidbar</a></li>
                        <li><a href="{% url 'blog:sefer_parsha_listing' 'Deuteronomy' %}">Devarim</a></li>
                        <li role="separator" class="divider"></li>
                    </ul>
                </li>
            </ul>
            <span class="BH">
        בס״ד
</span>
        </div>
        <!--/.nav-collapse -->

    </div>
</nav>
<div class="page-navbar">
    {% block page-navbar %}
    {% endblock %}
</div>
<div class="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

blog/templates/blog/chumash-parsha-list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% if books %}
        <ul>
        {% for key, value_list in books.items %}
            {{ key }}
            <ul>
            {% if value_list %}
                {% for value in value_list %}
                    <li>
                        {% with value.split|join:"_" as new_val %}

                        <a href="{% url 'blog:parsha_questions_list' new_val %}">{{ value }}</a>
                        {% endwith %}
                    </li>
                {% endfor %}
            {% else %}
                <li>No values</li>
            {% endif %}
            </ul>
        {% endfor %}
    {% else %}
        <p>There are no books.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% load staticfiles %}

{% block title %} The Shteig {% endblock %}

{% block header %}
 <link href="{% static 'blogindex.css' %}" rel="stylesheet">
{% endblock %}

{% block page-navbar %}
    <h2>{{ subheader }}</h2>
{% endblock %}

{% block content %}
    <h2>Posts</h2>
      {% for post in gemara_posts %}
        <div class="post">
           <h2>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h2>
            <p>
                Posted on
                <time datetime="{{ post.created|date:"c" }}">
                    {{ post.created|date }}
                </time>
            </p>
        </div>
    {% endfor %}
    <h1> Categories: </h1>
    {% for category in categories %}
        <div class="post">
            <a href="{% url 'blog:category_list' category.title %}">
                    {{ category.title }}
                </a>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/index_old.html
{% extends 'blog/base.html' %}

{% block title %} Blog Archive {% endblock %}

{% block content %}
    <h1> My Blog Archive </h1>
    {% for category in categories %}
        <div class="post">
            <h2>
               <!-- <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a> -->
            </h2>

            <p>{{ post.description }}</p>

            <h3>Category:
                {% for category in post.categories.all %}
                    <p>{{ category.title }}</p>
                {% endfor %}
            </h3>
            <p>
                Posted on
                <time datetime="{{ post.created|date:"c" }}">
                    {{ post.created|date }}
                </time>
            </p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/parsha_question_detail.html
{% extends 'blog/post.html' %}
{% load staticfiles %}

{% block header %}
    <link href="{% static 'parsha-question.css' %}" rel="stylesheet">
{% endblock %}
{% block page-navbar %}
    <h2>Parsha: {{ question.parsha.eng_name }}</h2>
{% endblock %}

{% block post %}
    <div class="article-wrapper">
        <div class="artcile-head">
            <h2>{{ question.title|title }}</h2>

            <h3>Parsha: {{ question.parsha.eng_name|title }}</h3>
        </div>
        <article>
            <p>{{ question.content|safe }}</p>
        </article>
    </div>
{% endblock %}

{% block right-side-bar %}
    {% if related_questions %}
        <h3>More Questions</h3>
        <ul>
            {% for q in related_questions %}
                <li><a href="{% url 'blog:parsha_question_detail' q.id %}">{{ q.title }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

blog/templates/blog/parsha_questions_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container">
        <a href="{% url 'blog:sefer_parsha_listing' sefer %}">&#8592;</a>

        <h2>{{ title }}</h2>

        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Question</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            {% if questions %}
                {% for question in questions %}
                    <tr>
                        <td>
                            <a href="{% url 'blog:parsha_question_detail' question.id %}">{{ question.title|title }}</a>
                        </td>
                        <td>{{ question.created|date:'Y-m-d' }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>No questions</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
{% endblock %}

blog/templates/blog/post-gemara.html
{% extends 'blog/post.html' %}

{% block page-navbar %}
    <h2>Gemara: {{ subheader }}</h2>
{% endblock %}

{% block post %}
    <article>
        <header>
        <div class="post-heading">
            <h1> {{ post.title }} </h1>

            <p>Daf: {{ post.daf }} </p>
            <p>Amud:
                {% if post.amud == '0' %}
                    &#1488;
                    {% else %}
                   &#1489;
                {% endif %}
            </p>
        </div>
            {% if post.statement_set %}
                <div class="section">
                    <h3>The Breakdown</h3>

                    <div class="inner">
                        {% for s in post.statement_set.all %}
                            <div class="jelly">
                                <p>{{ s.statement }}</p>

                                <p class="quote">~ {{ s.person.name }}</p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                <p>no statements exist</p>
            {% endif %}

            {% if post.content %}
                <div class="section">
                    <h3>Notes On the Daf</h3>

                    <div class="inner">
                        <div class="jelly">
                            <p>{{ post.content|safe }}</p>
                        </div>
                    </div>
                </div>
            {% endif %}
            <div class="section">
                <p>
                    Posted on
                    <time datetime="{{ post.created|date:"c" }}">
                        {{ post.created|date }}
                    </time>
                </p>
            </div>
        </header>
        <div class="section">
            <p class="description">
                {{ post.description }}
            </p>
        </div>
    </article>
{% endblock %}

{% block right-side-bar %}
    <h3>Related Post</h3>
    {% if related_posts %}
        {% for related_post in related_posts %}
            <a href="{{ related_post.get_absolute_url }}">
                {{ related_post.title }}
            </a>
        {% endfor %}
    {% else %}
        <p>No related posts</p>
    {% endif %}
{% endblock %}

blog/templates/blog/post-parsha.html
{% extends 'blog/post.html' %}

{% block page-navbar %}
    <h2>Sefer: {{ subheader }}</h2>
{% endblock %}

{% block post %}
<article>
<p>{{ post.content|safe }}</p>
</article>
{% endblock %}

{% block right-side-bar %}
{% endblock %}

blog/templates/blog/post.html
{% extends 'blog/base.html' %}

{% load staticfiles %}

{% block header %}
{% endblock %}


{% block title %}{{ post.title }}{% endblock %}
<p>Hello world</p>

{% block content %}
    <a href="{% url 'blog:parsha_questions_list' question.parsha.eng_name %}">&#8592;</a>
    <div class="container">
        {% block post %}
        {% endblock %}
    <div class="right-side-bar">
        {% block right-side-bar %}
        {% endblock %}
    </div>
    </div>
{% endblock %}

blog/templates/blog/sefer_parsha_listing.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container">
    <h2>{{ sefer }}</h2>

        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Parsha</th>
                <th>Number of Questions</th>
            </tr>
            </thead>
            <tbody>
            {% if parshas %}
                {% for parsha in parshas|dictsort:'parsha__order' %}
                    <tr>
                        <td>
                            {% with parsha.parsha__eng_name.split|join:"_" as new_val %}
                                <a href="{% url 'blog:parsha_questions_list' new_val %}">{{ parsha.parsha__eng_name|title }}</a>
                            {% endwith %}
                        </td>
                        <td>{{ parsha.total }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>No parshas</td>
                    <td>{{ parsha_count.Miketz.value }}</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
{% endblock %}

blog/templates/blog/table_listing.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container">
    <h2>{{ title }}</h2>

        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                {% for header in table_headers %}
                    <th>{{ header }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% if content %}
                {% for parsha in parshas|dictsort:'parsha__order' %}
                    <tr>
                        <td>
                            {% with parsha.parsha__eng_name.split|join:"_" as new_val %}
                                <a href="{% url 'blog:parsha_questions_list' new_val %}">{{ parsha.parsha__eng_name }}</a>
                            {% endwith %}
                        </td>
                        <td>{{ parsha.total }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>No parshas</td>
                    <td>{{ parsha_count.Miketz.value }}</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
{% endblock %}

blog/templates/blog/view_category.html
{% extends 'blog/base.html' %}
{% block head_title %}Viewing category {{ category.title }}{% endblock %}
{% block title %}{{ category.title }}{% endblock %}

{% block content %}
    {% if posts %}
        <ul>
        {% for post in posts %}
            <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no posts.</p>
    {% endif %}
{% endblock %}