ben_dev/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'home.views.index'),
    url(r'^hangman/', include('hangman.urls', namespace="hangman")),
    url(r'^plaid/', include('plaid_tester.urls', namespace="plaid_tester")),
    url(r'^admin/', include(admin.site.urls)),

]

blog/urls.py
__author__ = 'benfishman'

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^chumash_parsha/$', views.chumash_parsha_listing, name='chumash_parsha_listing'),
    url(r'^chumash_parsha/(?P<sefer>[-A-Za-z_-]+)/$', views.sefer_parsha_listing, name='sefer_parsha_listing'),
    url(r'^chumash_parsha/questions/(?P<parsha_name>[-A-Za-z_-]+)/$', views.parsha_questions_list, name='parsha_questions_list'),
    url(r'^parsha/question/(?P<question_id>[0-9]+)/$', views.parsha_question_detail, name='parsha_question_detail'),
    url(r'^(?P<slug>[\w\-]+)/$', views.post, name='blog_detail'),
    url(r'^category/(?P<category>[\w\-]+)/$', views.category_post_list, name='category_list'),

]

plaid_tester/urls.py
__author__ = 'benfishman'

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^data_dump/$', views.data_dump, name='data_dump'),
]

plaid_tester/models.py
from django.db import models

# Create your models here.

plaid_tester/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from plaid import Client
from plaid import errors as plaid_errors
from django.conf import settings
import sys


def index(request):
    return render(request, 'plaid_tester/index.html')


def data_dump(request):
    accounts = None
    transactions = None
    if request.method == 'POST':

        # print(request.POST)
        client = Client(client_id=settings.PLAID_CLIENT_ID, secret=settings.PLAID_SECRET)

        try:
            response = client.exchange_token(request.POST['public_token'])
            print(response.json())
        except:
            print(sys.exc_info()[0])


        try:
            response = client.upgrade('connect')
            print(response.json())
        except:
            print(sys.exc_info()[0])
        # client.access_token should now be populated with a
        # valid access_token;  we can make authenticated requests


        try:
            accounts = client.auth_get().json()['accounts']
        except:
            print(sys.exc_info()[0])
        # client.connect_get retrieves account data as  well!!
        try:
            transactions = client.connect_get().json()['transactions']
        except:
            print(sys.exc_info()[0])

    return render(request, 'plaid_tester/data_dump.html', {'accounts': accounts, 'transactions': transactions})

plaid_tester/templates/plaid_tester/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    {% block header %}
    {% endblock header %}
    <link href="{% static 'basic.css' %}" rel="stylesheet">
    <meta charset="UTF-8">
    <title>Plaid Testing</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

</head>
<body>
{% block content %}
{% endblock content %}

{% block script %}
{% endblock %}
</body>
</html>

plaid_tester/templates/plaid_tester/data_dump.html
{% extends 'plaid_tester/base.html' %}

{% load staticfiles %}

{% block header %}
    <!--<link href="{% static 'index.css' %}" rel="stylesheet">-->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

{% endblock header %}

{% block content %}
    <h3>{{ username }}</h3>
    <h3>Accounts</h3>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>institution</th>
            <th>subtype</th>
            <th>account number (last 4)</th>
            <th>name</th>
            <th>current balance</th>
            <th>available balance</th>
            <th>limit</th>
        </tr>
        </thead>
        <tbody>
        {% if accounts %}
            {% for a in accounts %}
            <tr>
                <td>{{ a.institution_type }}</td>
                <td>{{ a.subtype }}</td>
                <td>{{ a.meta.number }}</td>
                <td>{{ a.meta.name }}</td>
                <td>{{ a.balance.current }}</td>
                <td>{{ a.balance.available }}</td>
                <td>{{ a.meta.limit }}</td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td>No Accounts</td>
            </tr>
        {% endif %}
        </tbody>
    </table>

    <h3>Transactions</h3>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>date</th>
            <th>name</th>
            <th>amount</th>
            <th>category</th>
            <th>type</th>
            <th>pending</th>
        </tr>
        </thead>
        <tbody>
        {% if transactions %}
            {% for t in transactions %}
            <tr>
                <td>{{ t.date }}</td>
                <td>{{ t.name }}</td>
                <td>{{ t.amount }}</td>
                <td>{{ t.category }}</td>
                <td>{{ t.type }}</td>
                <td>{{ t.pending }}</td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td>No Transactions</td>
            </tr>
        {% endif %}
        </tbody>
    </table>

{% endblock content %}

plaid_tester/templates/plaid_tester/index.html
{% extends 'plaid_tester/base.html' %}

{% load staticfiles %}

{% block header %}
    <link href="{% static 'index2.css' %}" rel="stylesheet">
{% endblock header %}

{% block content %}
    <!-- A hidden input named public_token will be appended to this form
 once the user has completed the Link flow. Link will then submit the
 form, sending the public_token to your server. -->
    <form id="plaid-link" method="POST" action="{% url 'plaid_tester:data_dump' %}">
    {% csrf_token %}
    </form>

    <!-- To use Link with longtail institutions on Connect, set the
    data-longtail attribute to 'true'. See the Parameter Reference for
    additional documentation. -->
    <script
            src="https://cdn.plaid.com/link/stable/link-initialize.js"
            data-client-name="Client Name"
            data-form-id="plaid-link"
            data-key="test_key"
            data-product="auth"
            data-env="tartan">
    </script>
{% endblock content %}